### ISSUE TITLE
CapacityTester warning about System Volume Information

### ISSUE THREAD

**Issue by sampellino** [c0xc/CapacityTester#13]
![CapTester1](https://github.com/c0xc/CapacityTester/assets/5458241/b159dc2d-ef49-4e4d-84fa-320e774cae72)

Hi! I'm using your util on a Windows 10 machine, looking to verify the capacity of some MicroSD cards I got from Amazon. 

After using windows to format the SD card as NTFS _or_ as exFAT, I get a warning about System Volume Information being on the drive. I'm not certain that under Windows I'm able to do anything about that as a user. Not sure if the application should be ignoring this? 

If you need any additional information, feel free to ask. More than happy to help.

Thanks!

**Comment by c0xc** [comment]
Hi there! Thanks for letting me know about that issue. I will fix the check to ignore that directory on Windows. It's not important unless it consumes a significant amount of storage - but that won't be the case if you've just formatted the card. For now, hit ignore to continue.

Also, you may want to try the new ("destructive") disk test instead of this volume test. It'll wipe the card, so you'll have to reformat it afterwards. It will be very fast. It won't test every byte but it would be sufficient to detect a card that lies about its capacity.
