### ISSUE TITLE
Search USB flash is not always reliable

### ISSUE THREAD

**Issue by mmuruev** [c0xc/CapacityTester#22]
If you select destructive test it will complain that you have to unmount.. you do it.. after it attempt to became root (which isnt obvious!!!, to many popups!) and failed..no root dialog just complains - failed test. Switch back to regular test and now it complains that no drive but it present in selection dialog!

**Comment by c0xc** [comment]
Thanks for the feedback, but could you be a bit more specific? Are you saying it failed to acquire root privileges without even asking for a sudo password?
Acquiring root privileges should work the same way like in other applications, for example gparted. So if that's the issue, you could check if you can start gparted as non-root user.

Either way, what I could improve is the error message if it failed to acquire root privileges to make it obvious that it's not the disk test that failed.

> attempt to became root (which isnt obvious!!!, to many popups

As for the popup windows, I will consider removing them (at least the last one).

Before starting the test, a popup shows up, warning the user that the device will be overwritten. I deliberately made this warning annoying because you can actually wipe your hdd with this tool. But I guess I could remove the popup and display the warning in the window instead.

I'm going to change the user interface anyway, so that you don't have to go to Advanced for the disk test.

> Switch back to regular test and now it complains that no drive but it present in selection dialog!

So you click "Select drive" and the list of drives is empty?
Assuming it did _not_ fail to acquire root privileges when you tried the destructive disk test earlier, then that's expected because the disk test overwrites the filesystem on the USB device - the regular volume tests works on filesystems and because the filesystem is now gone, it's not listed anymore. In other words, you have to reformat it after running a disk test. To reformat, click on Advanced, Format drive.
Is that what you mean? If yes, it sounds like the program should offer to reformat when the disk test is done (as it is now, it just says that before the disk test is started). Other ideas are welcome, too.
If that's not what you mean, please explain.

**Comment by mmuruev** [comment]
What I mean menu is complicated, and switching between modes is not reliable. I don't remember exact sequence to reproduce. Probably not hard to find it. Because I bumped into it probably (monkey test will reveal this)

**Comment by c0xc** [comment]
The menu / design / navigation is going to change.
