### ISSUE TITLE
Ubuntu: "Disk test" - Full test - "** Stopping **" never aborts

### ISSUE THREAD

**Issue by Juksefantomet** [c0xc/CapacityTester#27]
I am running the capacity tester on ubuntu 22.04 with sudo.

Disk test - full test. 

I decided to abort and it's stuck on "stopping". I eventually had to disconnect the USB removable ssd for the program to actually quit.

The fun part is the progress is still running after it claims to be "stopping". So it seems to be continuing with some cycles before it's supposed to stop but it provides the enduser with no information about how long it will take or how much it has left before it's "done".

**Comment by c0xc** [comment]
Hi, thanks for the bug report.

I am aware of this flaw, at least if the program was not started as root. It should be fixed in the upcoming version (~v0.7). If you run CapacityTester as root, it should not happen anyway.

> The fun part is the progress is still running after it claims to be "stopping".

I have implemented a safeguard that'll make sure to stop the runaway subprocess (without having to detach the device, causing it to terminate).

**Comment by c0xc** [comment]
Closing issue. Please try [v0.7](https://github.com/c0xc/CapacityTester/releases/tag/v0.7), reopen if issue persists.
