### ISSUE TITLE
Spanish localization (es-ES).

### ISSUE THREAD

**Issue by caralu74** [c0xc/CapacityTester#3]
May I translate into Spanish?

**Comment by c0xc** [comment]
Thanks for the offer! Yes, sure. I was going to add a translation or two anyway...

**Comment by caralu74** [comment]
Thanks for your reply!
Now, Is there a .po or .xliff files?

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by c0xc** [comment]
I have prepared a German translation using standard `.ts` files and Qt Linguist, which I recommend. If you prefer XLIFF files, that's fine too. You can find both variations in the branch "3", subdirectory "[languages/](https://github.com/c0xc/CapacityTester/tree/3/languages)": capacitytester_es.ts capacitytester_es.xliff

Please pick one. Feel free to rename it to "capacitytester_spanish.ts". I'd then include it with that name and I've made sure that it'll pick it up as well (might be more obvious as long as there's no country distinction). Or you may use the iso language code + country, if necessary.
And let me know if I should provide translation comments.

**Comment by caralu74** [comment]
Translation finished!
The work is done, I hope it is Ok, of course some updates, new lines (or maybe mistyping ) could be translated. I think that if nobody complains there is no need to add translation comments.
Only the capacitytester_es.ts was edited.
I'll keep in touch!

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by caralu74** [comment]
Some minor mistakes (periods and colons).

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by c0xc** [comment]
Sounds good! Would you please commit the file languages/capacitytester_es.ts (or however you've named it) to the "3" branch?

**Comment by caralu74** [comment]
Thanks for your answer.
Into my Mail manager looks like the file is attached. But I'll resend it.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by caralu74** [comment]
Thanks for the work, I've got it now. I have added the translation to 
the feature branch. Here's a pre-built binary for Fedora.

I'll wait a bit before I merge it into the master in case something 
isn't ok. I've also noticed that I should probably change those places 
with numbers so that plural translations could be added as well ("1 
thing", "3 things" rather than "things: 3")...

**Comment by c0xc** [comment]
Thanks for the work, I've got it now. I have added the translation to
the feature branch.

I'll wait a bit before I merge it into the master in case something
isn't ok. I've also noticed that I should probably change those places
with numbers so that plural translations could be added as well ("1
thing", "3 things" rather than "things: 3")...

**Comment by c0xc** [comment]
Hi. I was ready to merge it but then I made some changes to allow for plurals. Would you be willing to update the three affected translations in each of the two source files? I have left your old translations in there, so they're shown with a gray arrow (and it says "source code not available", marked as vanished), so for each missing translation, you can find and copy the vanished one into the new, empty fields (shown with a question mark), you don't need to type it in again. You'll find it in the same place, same branch: [capacitytester_es.ts](https://github.com/c0xc/CapacityTester/raw/3/languages/capacitytester_es.ts)

Note that the texts with plural forms need to have `%n` rather than `%1` now (but Qt Linguist will warn you if there's a marker mismatch). Two translation fields are shown each, so just copy the old one into both and change them so that the first one is the singular form and the second one is the plural form. (I don't speak Spanish but I believe there's no third form.)

Afterwards, I'll make a release including at least one pre-built binary for Debian 7 (may also work on some other platforms, so you can just use it without having to run qmake and make).

**Comment by caralu74** [comment]
About plurals in Spanish your right, we have only one. Mostly ended in s or es.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by caralu74** [comment]
Well I will look into the files and translate or fix the strings. I hope it will no take so much time. Just way for 3 or 4 days please.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by c0xc** [comment]
Thanks in advance, I hope it's not too much trouble. You should not have to write anything new, just copy the "vanished" translations (in gray) and fix the endings.

**Comment by caralu74** [comment]
This isn't any trouble, is a pleasure first because It's free open source software, and second because it is a very useful tool.
I hope that there are no notable errors and help people to use it in Spanish.
If you need any other corrections, additions or improvements I will be more than willing.
Happy hacking!

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by caralu74** [comment]
I forget to delete the vanished lines I hope that there must be no problems

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by c0xc** [comment]
I'm glad you think it's a useful tool! I created it because I wanted to have a simple tool to identify fake usb sticks and I didn't like the alternatives. Anyway.
If you've already made the changes - I haven't received anything... You can just commit your file in the "3" branch but you may also attach the file or send it to me when you're ready.

**Comment by caralu74** [comment]
Hello!
I´ve attached the zip file with the _es_ES files, with plurals fixed.
[languages.zip](https://github.com/c0xc/CapacityTester/files/6071414/languages.zip)

**Comment by caralu74** [comment]
I think I committed them to the 3 branch.

**Comment by c0xc** [comment]
I haven't found your commit (forgot to push?) but instead, I've downloaded your zip file and added a thank you note in the commit message.
I have prepared a release which so far only includes a pre-compiled binary for Fedora 32. If you have another Linux distribution, you could try to run it but it may not work. I will add a pre-compiled binary for Debian and for Windows soon, so that users of those systems can just download and run the program without having to compile it first.
You can find it here: https://github.com/c0xc/CapacityTester/releases/tag/v0.2

Now, have you compiled the program with the new translation on your computer or do you have a Fedora system where you can run the pre-compiled binary to see if it looks ok? If so, does it show the Spanish interface on your system (without you having to set the environment variable `LANGUAGE=es`)?

**Comment by caralu74** [comment]
For this day's I can not compile or test, Sorry!

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by c0xc** [comment]
Sure, take your time. I totally understand if you don't have the time.

Do you use Debian or similar? If so, you won't necessarily have to compile it, just download and run (I'll add it soon).
